name             'nxlog_ce'
maintainer       'Simon Detheridge'
maintainer_email 'simon@widgit.com'
license          'Apache v2.0'
description      'Installs/Configures nxlog_ce'
long_description 'Installs/Configures nxlog_ce'
version          '0.1.0'
