name             'sc-nxlog'
version          '1.0.6'
description      'Installs and configures NXLog_ce on Linux or Windows'
issues_url       'https://github.com/sous-chefs/sc-nxlog/issues'
source_url       'https://github.com/sous-chefs/sc-nxlog'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
chef_version      '>= 16.0'

supports         'ubuntu', '>= 16.04'
supports         'debian', '>= 9.0'
supports         'redhat', '>= 7.0'
supports         'centos', '>= 7.0'
supports         'windows'
