name             'nxlog'
maintainer       'Simon Detheridge'
maintainer_email 'simon@widgit.com'
license          'Apache v2.0'
description      'Installs/Configures nxlog'
long_description 'Installs/Configures nxlog'
version          '0.1.0'
